#+TITLE: Emacs Personal Config
#+AUTHOR: FLÁVIO MUNIZ
#+STARTUP: showeverything

* Table of Contents :toc:
- [[#scripts][Scripts]]
  - [[#scripts-path][Scripts Path]]
- [[#themes][Themes]]
  - [[#catppuccin][Catppuccin]]
  - [[#ewal-default][Ewal (Default)]]
- [[#general-settings][General Settings]]
  - [[#disable-auto-save-and-auto-backup][Disable Auto Save and Auto Backup]]
  - [[#disable-startup-message-tools-scroll-and-menu-bar][Disable Startup Message, Tools, Scroll and Menu Bar]]
  - [[#editor-config][Editor Config]]
  - [[#enable-columnline-number-and-truncated-lines][Enable Column/Line Number and Truncated Lines]]
  - [[#enable-eletric-indent][Enable Eletric Indent]]
  - [[#full-screen-at-startup][Full Screen at Startup]]
  - [[#self-closing-parenthesis][Self-Closing Parenthesis]]
  - [[#use-yn-in-prompts][Use y/n in Prompts]]
- [[#font][Font]]
  - [[#font-face][Font Face]]
  - [[#nerd-icons][Nerd Icons]]
- [[#key-bindings][Key Bindings]]
  - [[#general][General]]
  - [[#buffer][Buffer]]
  - [[#files][Files]]
  - [[#help][Help]]
  - [[#others][Others]]
  - [[#projectile][Projectile]]
  - [[#text][Text]]
  - [[#toogle][Toogle]]
  - [[#undo][Undo]]
- [[#git][Git]]
  - [[#magit][Magit]]
  - [[#git-time-machine][Git Time Machine]]
- [[#org-mode][Org Mode]]
  - [[#toc][Toc]]
  - [[#enable-org-bullets][Enable Org Bullets]]
  - [[#org-tempo-block-tag-expansion][Org Tempo (Block Tag Expansion)]]
- [[#packages][Packages]]
  - [[#ace-window][Ace Window]]
  - [[#buffer-move][Buffer Move]]
  - [[#cape][Cape]]
  - [[#centaur-tabs][Centaur Tabs]]
  - [[#corfu][Corfu]]
  - [[#dashboard][Dashboard]]
  - [[#diminish][Diminish]]
  - [[#dired][Dired]]
  - [[#doom-modeline][Doom Modeline]]
  - [[#eglot][Eglot]]
  - [[#exec-path-from-shell][Exec Path From Shell]]
  - [[#flycheck][Flycheck]]
  - [[#flycheck-eglot][Flycheck-Eglot]]
  - [[#gptel][Gptel]]
  - [[#highlight-indent-guides][Highlight Indent Guides]]
  - [[#imenu-list][Imenu List]]
  - [[#ivycounselswiper][Ivy/Counsel/Swiper]]
  - [[#move-text][Move-text]]
  - [[#neotree][Neotree]]
  - [[#paredit][Paredit]]
  - [[#projectile-1][Projectile]]
  - [[#rainbow-delimiters][Rainbow Delimiters]]
  - [[#repeat-mode][Repeat Mode]]
  - [[#sudo-edit][Sudo Edit]]
  - [[#treesit-auto][Treesit-auto]]
  - [[#web-mode][Web Mode]]
  - [[#which-key][Which-Key]]
  - [[#zoom][Zoom]]
- [[#languages][Languages]]
  - [[#cc][C/C++]]
  - [[#haskell][Haskell]]
  - [[#standard-ml-sml][Standard ML (SML)]]
  - [[#mardown][Mardown]]
  - [[#ocaml][OCaml]]
  - [[#python][Python]]
  - [[#qml][Qml]]
  - [[#racket][Racket]]
  - [[#shell-scripts][Shell Scripts]]
- [[#terminals][Terminals]]
  - [[#eshell][Eshell]]
  - [[#vterm-and-vterm-toggle][Vterm and Vterm Toggle]]

* Scripts
** Scripts Path
#+begin_src emacs-lisp
  (add-to-list 'load-path "~/.config/emacs/scripts/")
#+end_src

* Themes
** Catppuccin
#+begin_src emacs-lisp
  (use-package catppuccin-theme
    :ensure t
    :custom
    (catppuccin-flavor 'mocha))
#+end_src

** Ewal (Default)
Dynamic theme based on pywal16 generated colors. 
#+begin_src emacs-lisp
  ;; Pywal/Ewal
  (use-package ewal
    :ensure t
    :custom
    (ewal-use-builtin-always-p nil)
    (ewal-force-tty-colors-in-daemon-p nil))

  (use-package ewal-spacemacs-themes
    :ensure t
    :config
    (load-theme 'ewal-spacemacs-modern t)
    (enable-theme 'ewal-spacemacs-modern))

  ;; Start ewal colors file watcher
  (require 'ewal-auto-update)
  (my/start-ewal-auto-update)
#+end_src

* General Settings

** Disable Auto Save and Auto Backup
#+begin_src emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+end_src

** Disable Startup Message, Tools, Scroll and Menu Bar
#+begin_src emacs-lisp
  (setq inhibit-splash-screen t)
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** Editor Config
#+begin_src emacs-lisp
  (editorconfig-mode t)
#+end_src

** Enable Column/Line Number and Truncated Lines
#+begin_src emacs-lisp
  (column-number-mode 1)
  (global-display-line-numbers-mode 1)
  (setq display-line-numbers-type 'relative)
  (global-visual-line-mode 1)
#+end_src

** Enable Eletric Indent
#+begin_src emacs-lisp
  (electric-indent-mode 1)
#+end_src

** Full Screen at Startup
#+begin_src emacs-lisp
  (add-hook 'window-setup-hook
            'toggle-frame-maximized t)
#+end_src

** Self-Closing Parenthesis
#+begin_src emacs-lisp
  (electric-pair-mode 1)
#+end_src

** Use y/n in Prompts
#+begin_src emacs-lisp
  (setq use-short-answers t)
#+end_src

* Font
Define emacs fonts.

** Font Face
Set custom font, and makes all comments be in italic.
#+begin_src emacs-lisp
  (set-face-attribute 'default nil
  					:font "UbuntuMono Nerd Font"
  					:height 140
  					:weight 'regular)

  (set-face-attribute 'font-lock-comment-face nil
  					:slant 'italic)

  (add-to-list 'default-frame-alist
  			 '(font . "UbuntuMono Nerd Font-14"))
#+end_src

** Nerd Icons
#+begin_src emacs-lisp
  (use-package nerd-icons
    ;; :custom
    ;; The Nerd Font you want to use in GUI
    ;; "Symbols Nerd Font Mono" is the default and is recommended
    ;; but you can use any other Nerd Font if you want
    ;; (nerd-icons-font-family "Symbols Nerd Font Mono")
    )

  (use-package nerd-icons-dired
    :hook
    (dired-mode . nerd-icons-dired-mode))

  (use-package nerd-icons-ivy-rich
    :ensure t
    :init
    (nerd-icons-ivy-rich-mode 1))

  (use-package nerd-icons-corfu
    :ensure t)
#+end_src

* Key Bindings
Definitions of Almost all Key Bindings Used in this Config.

** General
Define "C-c" as leader key.
#+begin_src emacs-lisp
  (use-package general
    :ensure t
    :config
    (general-create-definer my-leader-def
      :prefix "C-c"
      :keymaps 'override))
#+end_src

** Buffer
*** Ace Window
#+begin_src emacs-lisp
  ;; Ace Window
  (defun ace-window-prefix ()
    "Use `ace-window' to display the buffer of the next command.
  The next buffer is the buffer displayed by the next command invoked
  immediately after this command (ignoring reading from the minibuffer).
  Creates a new window before displaying the buffer.
  When `switch-to-buffer-obey-display-actions' is non-nil,
  `switch-to-buffer' commands are also supported."
    (interactive)
    (display-buffer-override-next-command
     (lambda (buffer _)
       (let (window type)
         (setq
          window (aw-select (propertize " ACE" 'face 'mode-line-highlight))
          type 'reuse)
         (cons window type)))
     nil "[ace-window]")
    (message "Use `ace-window' to display next command buffer..."))

  (keymap-global-set "C-M-o" 'ace-window-prefix)
  (keymap-global-set "M-o"   'ace-window)
#+end_src

*** Buffer Move
#+begin_src emacs-lisp
    ;; Buffer Move
  (my-leader-def
    "<up>"    '(buf-move-up    :wk "Swap current buffer with the top one")
    "<down>"  '(buf-move-down  :wk "Swap current buffer with the bottom one")
    "<left>"  '(buf-move-left  :wk "Swap current buffer with the left one")
    "<right>" '(buf-move-right :wk "Swap current buffer with the right one"))
#+end_src

*** Centaur Tabs
#+begin_src emacs-lisp

  ;; Centaur Tabs
  (keymap-global-set "C-<" 'centaur-tabs-backward)
  (keymap-global-set "C->" 'centaur-tabs-forward)

  (my-leader-def
    "b" '(centaur-tabs-counsel-switch-group :wk "Switch centaur tab group"))
#+end_src

*** C-x k Will Kill Current Buffer
#+begin_src emacs-lisp
  (defun bjm/kill-this-buffer ()
    "Kill the current buffer."
    (interactive)
    (kill-buffer (current-buffer)))

  (keymap-global-set "C-x k" 'bjm/kill-this-buffer)
#+end_src

** Files
#+begin_src emacs-lisp
  ;; File find/edit
  (my-leader-def
    "f" '(:ignore t :wk "find/edit") 
    "f c" '((lambda () (interactive) 
  			(find-file "~/.config/emacs/config.org")) 
  		  :wk "Open emacs config file")
    "f i" '((lambda () (interactive) 
  			(find-file "~/.config/emacs/init.el"))
  			:wk "Open emacs init file")
    "f s" '(sudo-edit-find-file :wk "Sudo find file")
    "f S" '(sudo-edit :wk "Sudo edit file")
    "f r" '(counsel-recentf :wk "find recent files")
    "f g" '(counsel-grep-or-swiper :wk "Search for string in current file"))

  ;; Locate
  (keymap-global-set "C-x l" 'counsel-locate)
#+end_src

** Help
#+begin_src emacs-lisp
  (my-leader-def
    "h" '(:ignore t :wk "Help")
    "h f" '(counsel-describe-function :wk "Describe function")
    "h v" '(counsel-describe-variable :wk "Describe variable")
    "h s" '(counsel-describe-symbol   :wk "Describe symbol")
    "h m" '(describe-mode             :wk "Describe mode")
    "h i" '(info                      :wk "Info"))
#+end_src

** Others
#+begin_src emacs-lisp
  ;; Reload emacs config
  (my-leader-def
    "r" '((lambda () (interactive) (org-babel-load-file (expand-file-name "~/.config/emacs/config.org"))) :wk "Reload emacs config"))
#+end_src

** Projectile
#+begin_src emacs-lisp
  ;; Projectile
  (my-leader-def
    "p" '(projectile-command-map :wk "Projectile"))
#+end_src

** Text
#+begin_src emacs-lisp
  (defun smart-line-beginning ()
    "Move point to the beginning of text on the current line; if that is already
    the current position of point, then move it to the beginning of the line."
    (interactive)
    (let ((pt (point)))
    	(beginning-of-line-text)
      (when (eq pt (point))
        (beginning-of-line))))

  (defun phg/kill-to-bol ()
    "Kill from point to beginning of line."
    (interactive)
    (kill-line 0))

  ;; Bind dor moving to start of the line respecting identation
  (keymap-global-set "C-a" 'smart-line-beginning)

  ;; Bind for Killing from pointer to start of line
  (keymap-global-set "C-<backspace>" 'phg/kill-to-bol)

  ;; Zoom In/Out
  (keymap-global-set "C-="            'text-scale-increase)
  (keymap-global-set "C--"            'text-scale-decrease)
  (keymap-global-set "C-<wheel-up>"   'text-scale-increase)
  (keymap-global-set "C-<wheel-down>" 'text-scale-decrease)

  ;; Swap default isearch for swiper-isearch
  (keymap-global-set "C-s" #'swiper-isearch)

  ;; Comment Lines
  (my-leader-def
    "TAB TAB" '(comment-line :wk "Comment lines"))

#+end_src

** Toogle
Commands that open new windows and can be opened/closed via a toggler.
#+begin_src emacs-lisp
  ;; Open eshell
  (keymap-global-set "<f9>" 'eshell)

  ;; Open vterm
  (keymap-global-set "<f10>" 'vterm-toggle)

  ;; Neotree
  (keymap-global-set "<f8>" 'neotree-toggle)

  ;; Imenu List
  (keymap-global-set "M-'" 'imenu-list-smart-toggle)
#+end_src

** Undo
Bind undo to Ctrl-z.
#+begin_src emacs-lisp
  (keymap-global-set "C-z" 'undo)
#+end_src


* Git

** Magit
#+begin_src emacs-lisp
  (use-package magit
    :ensure t)
#+end_src

** Git Time Machine
#+begin_src emacs-lisp
  (use-package git-timemachine
    :ensure t)
#+end_src

* Org Mode
** Toc
Allows us to create a Table of Contents in our Org docs.
#+begin_src emacs-lisp
  (use-package toc-org
    :ensure t
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src

** Enable Org Bullets
Org-bullets gives us attractive bullets rather than asterisks.
#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
  (use-package org-bullets
    :ensure t)
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

** Org Tempo (Block Tag Expansion)
Org-tempo is not a separate package but a module within org that can be enabled.  Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.  Other expansions available include:

| Typing the below + TAB | Expands to ...                          |
|------------------------+-----------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |

#+begin_src emacs-lisp 
(require 'org-tempo)
#+end_src

* Packages

** Ace Window
Quickly switch windows in Emacs.
#+begin_src emacs-lisp
  (use-package ace-window
    :ensure t
    :custom
    ;; Set Group of Keys For Windows
    (aw-keys '(?q ?w ?e ?r ?t ?y ?u ?i ?o ?p))
    :config
    (ace-window-display-mode 1))
#+end_src

** Buffer Move
This file is for lazy people wanting to swap buffers without typing C-x b on each window.
#+begin_src emacs-lisp
  (use-package buffer-move
    :ensure t)
#+end_src

** Cape
Cape provides Completion At Point Extensions which can be used in combination with Corfu, Company or the default completion UI. The completion backends used by completion-at-point are so called completion-at-point-functions (Capfs).
#+begin_src emacs-lisp
  (use-package cape
    :ensure t
    :init
    (add-to-list 'completion-at-point-functions #'cape-dabbrev)
    (add-to-list 'completion-at-point-functions #'cape-file)
    (add-to-list 'completion-at-point-functions #'cape-elisp-block))
#+end_src

** Centaur Tabs
This projects aims to become an aesthetic, functional and efficient tabs plugin for Emacs with a lot of customization options.
#+begin_src emacs-lisp
  (use-package centaur-tabs
    :ensure t
    :demand
    :custom
    (centaur-tabs-style "bar")
    (centaur-tabs-set-bar 'left)
    (centaur-tabs-icon-type 'nerd-icons)
    (centaur-tabs-set-icons t)
    (centaur-tabs-gray-out-icons 'buffer)
    (centaur-tabs-set-modified-marker t)
    (centaur-tabs-label-fixed-length 12)
    (centaur-tabs-cycle-scope 'tabs)
    :config
    (centaur-tabs-mode t)
    (centaur-tabs-group-by-projectile-project)
    :hook
    (dashboard-mode        . centaur-tabs-local-mode)
    (term-mode             . centaur-tabs-local-mode)
    (vterm-mode            . centaur-tabs-local-mode)
    (gptel-mode            . centaur-tabs-local-mode)
    (neotree-mode          . centaur-tabs-local-mode)
    (imenu-list-major-mode . centaur-tabs-local-mode))
#+end_src

** Corfu
Corfu enhances in-buffer completion with a small completion popup. The current candidates are shown in a popup below or above the point, and can be selected by moving up and down. Corfu is the minimalistic in-buffer completion counterpart of the Vertico minibuffer UI.
#+begin_src emacs-lisp
  (use-package corfu
    :ensure t
    :custom
    (corfu-auto t)
    ;;(corfu-preselect 'directory)
    (corfu-auto-delay 0.1)
    (corfu-preview-current nil)
    :init
    (global-corfu-mode)
    :config
    ;; Free the RET key for less intrusive behavior.
    ;; Option 1: Unbind RET completely
    ;; (keymap-unset corfu-map "RET")
    ;; Option 2: Use RET only in shell modes
    (keymap-set corfu-map "RET" `( menu-item "" nil :filter
  								 ,(lambda (&optional _)
  									(and (derived-mode-p 'eshell-mode 'comint-mode)
  										 #'corfu-send)))))

  (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter)

  (when (<= emacs-major-version 31)
    (use-package corfu-terminal
  	:ensure t
  	:config
  	(unless (display-graphic-p)
  	  corfu-terminal-mode +1)))
#+end_src

** Dashboard
Emacs Dashboard is an extensible startup screen showing you recent files, bookmarks, agenda items and an Emacs banner.
#+begin_src emacs-lisp
  (use-package dashboard
    :ensure t 
    :custom
    (dashboard-modify-heading-icons '((recents . "file-text")
                                      (bookmarks . "book")))
    (initial-buffer-choice 'dashboard-open)
    (dashboard-icon-types 'nerd-icons)
    (dashboard-set-heading-icons t)
    (dashboard-set-file-icons t)
    (dashboard-display-icons-p t)
    
    ;;(setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
    (dashboard-startup-banner 'logo)
    (dashboard-center-content t)

    (dashboard-projects-backend 'projectile)
    
    (dashboard-items '((recents . 5)
  					 (projects . 3)
                       (bookmarks . 3)))
    :config
    (dashboard-setup-startup-hook))
#+end_src

** Diminish
This package implements hiding or abbreviation of the modeline displays (lighters) of minor-modes.  With this package installed, you can add ‘:diminish’ to any use-package block to hide that particular mode in the modeline.
#+begin_src emacs-lisp
  (use-package diminish
    :ensure t)
#+end_src

** Dired
#+begin_src emacs-lisp
  (use-package dired-open
    :ensure t
    :config
    (setq dired-open-extensions '(("gif" . "xviewer")
                                  ("jpg" . "xviewer")
                                  ("png" . "xviewer")
                                  ("mkv" . "mpv")
                                  ("mp4" . "mpv"))))
#+end_src

** Doom Modeline
A fancy and fast mode-line inspired by minimalism design.
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :custom
    (doom-modeline-project-detection 'auto)
    (doom-modeline-buffer-file-name-style 'realative-from-project)
    (doom-modeline-major-mode-icon t)
    (doom-modeline-lsp t)
    (doom-modeline-lsp-icon t)
    (doom-modeline-buffer-name t)
    (doom-modeline-minor-modes nil)
    (doom-modeline-total-line-number t)
    (doom-modeline-percent-position nil)
    :init 
    (doom-modeline-mode 1))
#+end_src

** Eglot
A client for Language Server Protocol servers.
#+begin_src emacs-lisp
    (use-package eglot
      :ensure t
  	:config
  	(add-hook 'prog-mode-hook 'eglot-ensure))
#+end_src

** Exec Path From Shell
A GNU Emacs library to ensure environment variables inside Emacs look the same as in the user's shell.
#+begin_src emacs-lisp
  (use-package exec-path-from-shell
    :ensure t
    :config 
    (exec-path-from-shell-initialize))
#+end_src

** Flycheck
Modern on-the-fly syntax checking extension for GNU Emacs.
#+begin_src emacs-lisp
  (use-package flycheck
    :ensure t
    :init 
    (global-flycheck-mode +1))
#+end_src

** Flycheck-Eglot
A simple “glue” minor mode that allows Flycheck and Eglot to work together. Thus, the Flycheck frontend can display the results of syntactic checks performed by the LSP server.
#+begin_src emacs-lisp
  (use-package flycheck-eglot
    :ensure t
    :after (flycheck eglot)
    :config
    (global-flycheck-eglot-mode 1))
#+end_src

** Gptel
gptel is a simple Large Language Model chat client for Emacs, with support for multiple models and backends. It works in the spirit of Emacs, available at any time and uniformly in any buffer.
#+begin_src emacs-lisp
  ;; Check package repo for more options
  ;; https://github.com/karthink/gptel
  (use-package gptel
    :ensure t
    :config
    (setq
     gptel-backend (gptel-make-gemini "Gemini" 
  				   :key 'gptel-api-key-from-auth-source 
  				   :stream t)))
#+end_src

** Highlight Indent Guides
This minor mode highlights indentation levels via font-lock. Indent widths are dynamically discovered, which means this correctly highlights in any mode, regardless of indent width, even in languages with non-uniform indentation such as Haskell. By default, this mode also inspects your theme dynamically, and automatically chooses appropriate colors for highlighting. This mode works properly around hard tabs and mixed indentation, and it behaves well in large buffers.
#+begin_src emacs-lisp
  (use-package highlight-indent-guides
    :ensure t
    :defer t
    :hook (prog-mode . highlight-indent-guides-mode)
    :config
    (setq highlight-indent-guides-method 'character)
    (setq highlight-indent-guides-character ?\|)
    (setq highlight-indent-guides-responsive 'stack)
    (setq highlight-indent-guides-auto-character-face-perc 80))
#+end_src

** Imenu List
This Emacs minor-mode creates an automatically updated buffer called *Ilist* that is populated with the current buffer's imenu entries. The *Ilist* buffer is typically shown as a sidebar (Emacs vertically splits the window).
#+begin_src emacs-lisp
   (use-package imenu-list
     :ensure t
     :custom
     (imenu-list-focus-after-activation t)
     (imenu-list-auto-resize t)
     (imenu-list-position 'left)
     :hook
     (imenu-list-major-mode . (lambda ()(display-line-numbers-mode -1))))


   ;; Make imenu-list size stable
   (defun my/fix-imenu-size ()
     (with-selected-window (get-buffer-window "*Ilist*")
       (setq window-size-fixed 'width)
       (window-resize (selected-window) (- 30 (window-total-width)) t t)))

   (add-hook 'imenu-list-update-hook 'my/fix-imenu-size)
#+end_src

** Ivy/Counsel/Swiper
Ivy is a generic completion mechanism for Emacs. While it operates similarly to other completion schemes such as icomplete-mode, Ivy aims to be more efficient, smaller, simpler, and smoother to use yet highly customizable.

Counsel takes this further, providing versions of common Emacs commands that are customized to make the best use of Ivy. 

Swiper is an alternative to Isearch that uses Ivy to show an overview of all matches.
#+begin_src emacs-lisp
  (use-package counsel
    :ensure t
    :diminish
    :after ivy
    :custom
    (ivy-initial-inputs-alist nil) ;; Remove starting ^ regex in M-x
    :config 
    (counsel-mode))

  (use-package ivy
    :ensure t
    :diminish
    :bind
    ;; ivy-resume resumes the last Ivy-based completion.
      (("C-c C-r" . ivy-resume)
      ("C-x B" . ivy-switch-buffer-other-window))
    :custom
      (setq ivy-use-virtual-buffers t)
      (setq ivy-count-format "(%d/%d) ")
      (setq enable-recursive-minibuffers t)
    :config
      (ivy-mode))

  (use-package ivy-rich
    :ensure t
    :after ivy
    :init (ivy-rich-mode 1) ;; this gets us descriptions in M-x.
    :custom
    (ivy-virtual-abbreviate 'full)
    (ivy-rich-switch-buffer-align-virtual-buffer t)
    (ivy-rich-path-style 'abbrev))
#+end_src

** Move-text
MoveText allows you to move the current line using M-up / M-down (or any other bindings you choose) if a region is marked, it will move the region instead.
#+begin_src emacs-lisp
  (use-package move-text
    :ensure t
    :config (move-text-default-bindings))

  (defun indent-region-advice (&rest ignored)
    (let ((deactivate deactivate-mark))
      (if (region-active-p)
          (indent-region (region-beginning) (region-end))
        (indent-region (line-beginning-position) (line-end-position)))
      (setq deactivate-mark deactivate)))

  (advice-add 'move-text-up :after 'indent-region-advice)
  (advice-add 'move-text-down :after 'indent-region-advice)
#+end_src

** Neotree
A emacs tree plugin like NerdTree for Vim.
#+begin_src emacs-lisp
  (use-package neotree
    :ensure t
    :config
    (setq neo-smart-open t
          neo-show-hidden-files t
          neo-window-width 40
          neo-window-fixed-size nil
          inhibit-compacting-font-caches t
          projectile-switch-project-action 'neotree-projectile-action)

    ;; Neotree configs set at time of execution
    ;; - Truncate long file names
    ;; - Neo-Theme: icons (graphic), classic (terminal)
    ;; - Display Line Number Mode -1
    (add-hook 'neo-after-create-hook
              #'(lambda (_)
                  (with-current-buffer (get-buffer neo-buffer-name)
                    (setq truncate-lines t)
                    (setq word-wrap nil)
  				  (setq neo-theme 'nerd-icons)
  				  (display-line-numbers-mode -1)
                    (make-local-variable 'auto-hscroll-mode)
  				  (setq auto-hscroll-mode nil)))))
#+end_src

** Paredit
Minor mode for editing parentheses.
#+begin_src emacs-lisp
  (use-package paredit
    :ensure t)

  (add-hook 'racket-mode-hook 'enable-paredit-mode)
  (add-hook 'racket-repl-mode-hook 'enable-paredit-mode)
  (add-hook 'emacs-lisp-mode-hook 'enable-paredit-mode)

  ;; Remove Key Bindings that interfers with iteractives modes
  (dolist (k '("RET" "C-m" "C-j"))
    (define-key paredit-mode-map (kbd k) nil))
#+end_src

** Projectile
Projectile is a project interaction library for Emacs. It provides a powerful set of features operating at the project level, as well as simple heuristics to identify projects.
#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :diminish
    :config (projectile-mode 1))
#+end_src

** Rainbow Delimiters
rainbow-delimiters is a "rainbow parentheses"-like mode which highlights delimiters such as parentheses, brackets or braces according to their depth. Each successive level is highlighted in a different color. This makes it easy to spot matching delimiters, orient yourself in the code, and tell which statements are at a given depth.
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :ensure t)

  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
#+end_src

** Repeat Mode
Buitin mode for repeating commands in emacs.
#+begin_src emacs-lisp
  (use-package repeat
	:config
	(repeat-mode 1)
	:custom
	(repeat-too-dangerous '(kill-this-buffer))
	(repeat-exit-timeout 5))
#+end_src

** Sudo Edit
Utilities for opening files with sudo.
#+begin_src emacs-lisp
  (use-package sudo-edit
    :ensure t)
#+end_src

** Treesit-auto
Automatically install and use tree-sitter major modes in Emacs 29+. If the tree-sitter version can’t be used, fall back to the original major mode.
#+begin_src emacs-lisp
  (use-package treesit-auto
    :ensure t
    :custom
    (treesit-auto-install 'prompt))
#+end_src

** Web Mode
web-mode.el is an emacs major mode for editing web templates aka HTML files embedding parts (CSS/JavaScript) and blocks (pre rendered by client/server side engines).

web-mode.el is compatible with many template engines: PHP, JSP, ASP, Django, Twig, Jinja, Mustache, ERB, FreeMarker, Velocity, Cheetah, Smarty, CTemplate, Mustache, Blade, ErlyDTL, Go Template, Dust.js, Google Closure (soy), React/JSX, Angularjs, ejs, Nunjucks, etc.
#+begin_src emacs-lisp
  (use-package web-mode
    :ensure t
    :config
    (add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
    (setq
     web-mode-markup-indent-offset 2
     web-mode-css-indent-offset 2
     web-mode-code-indent-offset 2
     web-mode-style-padding 2
     web-mode-script-padding 2
     web-mode-enable-auto-closing t
     web-mode-enable-auto-opening t
     web-mode-enable-auto-pairing t
     web-mode-enable-auto-indentation t)
    :mode 
    (("\\.html\\'" . web-mode)
       ("\\.php\\'" . web-mode)
       ("\\.tsx\\'" . web-mode)))
#+end_src

** Which-Key
Minor mode for Emacs that displays the key bindings following your currently entered incomplete command (a prefix) in a popup.
#+begin_src emacs-lisp
  (use-package which-key
    :diminish
    :custom
    (which-key-side-window-location 'bottom)
    (which-key-sort-order #'which-key-key-order-alpha)
    (which-key-sort-uppercase-first nil)
    (which-key-add-column-padding 1)
    (which-key-max-display-columns nil)
    (which-key-min-display-lines 6)
    (which-key-side-window-slot -10)
    (which-key-side-window-max-height 0.25)
    (which-key-idle-delay 0.8)
    (which-key-max-description-length 25)
    (which-key-allow-imprecise-window-fit nil)
    (which-key-separator " → " )
    :init  
    (which-key-mode 1))
#+end_src

** Zoom
This minor mode takes care of managing the window sizes by enforcing a fixed and automatic balanced layout where the currently selected window is resized according to zoom-size which can be an absolute value in lines/columns, a ratio between the selected window and frame size or even a custom callback.
#+begin_src emacs-lisp
  (defun my-zoom-predicate-p ()
    "Return t if the current buffer has fewer than 20 lines."
    (< (count-lines (point-min) (point-max)) 20))

  (use-package zoom
    :ensure t
    :init
    (zoom-mode t)
    :custom
    (zoom-ignored-major-modes '(ivy-posframe-mode))
    (zoom-size '(0.618 . 0.618))
    (zoom-ignore-predicates '(my-zoom-predicate-p)))
#+end_src

* Languages
Adds support to various programming languages.

** C/C++
*** LSP (Eglot)
#+begin_src emacs-lisp
  (add-to-list 'eglot-server-programs 
    	     '((c++-mode c-mode) "clangd"))
#+end_src

** Haskell
*** Major Mode
#+begin_src emacs-lisp
  (use-package haskell-mode
    :ensure t
    :config
    (add-hook 'haskell-mode-hook 'interactive-haskell-mode))
#+end_src

*** LSP (Eglot)
#+begin_src emacs-lisp
  (add-to-list 'eglot-server-programs
               '(haskell-mode . ("haskell-language-server-wrapper" "--lsp")))
#+end_src

** Standard ML (SML)
*** Major Mode
#+begin_src emacs-lisp
  (use-package sml-mode
    :ensure t)
#+end_src

** Mardown
*** Major Mode
#+begin_src emacs-lisp
  (use-package markdown-mode
    :ensure t
    :init (setq markdown-command "multimarkdown")
    :bind (:map markdown-mode-map
                ("C-c C-e" . markdown-do))
    :config
    (add-to-list 'auto-mode-alist '("README\\.md\\'" . gfm-mode))
    (add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode))
    (add-to-list 'auto-mode-alist '("\\.markdown\\'" . markdown-mode)))
#+end_src

** OCaml
*** Major Mode
#+begin_src emacs-lisp
  (use-package caml
    :ensure t)

  (use-package tuareg
    :ensure t
    :mode (("\\.ocamlinit\\'" . tuareg-mode)))
#+end_src

** Python
*** Tools
#+begin_src emacs-lisp
  ;;Python virtual environments for emacs.
  ;;Use M-x pyvenv-workon to change python version to local. 
  (use-package pyvenv
    :ensure t
    :init
    (setenv "WORKON_HOME" "~/.pyenv/versions"))
#+end_src

** Qml
*** Major Mode
#+begin_src emacs-lisp
  (use-package qml-mode
    :ensure t)

  (add-to-list 'auto-mode-alist '("\\.qml\\'" . qml-mode))
#+end_src

*** LSP (Eglot)
#+begin_src emacs-lisp
  (add-to-list 'eglot-server-programs
  	     '((qml-mode qml-ts-mode) "qmlls6"))
#+end_src

** Racket
*** Major Mode
#+begin_src emacs-lisp
  (use-package racket-mode
    :ensure t)
#+end_src

** Shell Scripts
*** LSP (Eglot)
#+begin_src emacs-lisp
  ;; Shell Scripts
  (add-to-list 'eglot-server-programs
      		 '((sh-mode bash-ts-mode) "bash-language-server" "start"))
#+end_src

* Terminals

** Eshell
#+begin_src emacs-lisp
  (use-package eshell-syntax-highlighting
    :ensure t
    :after esh-mode
    :config (eshell-syntax-highlighting-global-mode 1))

  (setq scrool-to-bottom-on-input t
        eshell-history-size 5000
        eshell-buffer-maximun-lines 5000)
#+end_src

** Vterm and Vterm Toggle
Install CMake, libtools and libvterm before if errors occurs.

#+begin_src emacs-lisp
  (use-package vterm
    :ensure t
    :config
    (setq shell-file-name "/bin/zsh"
          vterm-max-scrollback 5000))

  (use-package vterm-toggle
    :ensure t
    :after vterm
    :config
    (setq vterm-toggle-fullscreen-p nil)
    (setq vterm-toggle-scope 'project)
    (add-to-list 'display-buffer-alist
                 '((lambda (buffer-or-name _)
                       (let ((buffer (get-buffer buffer-or-name)))
                         (with-current-buffer buffer
                           (or (equal major-mode 'vterm-mode)
                               (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                    (display-buffer-reuse-window display-buffer-at-bottom)
                    (reusable-frames . visible)
                    (window-height . 0.3))))
#+end_src
